AWSTemplateFormatVersion: 2010-09-09
Description: Zscaler Cloud Connector Pre-Deployment Macro Template
Metadata:
  LICENSE: 'Apache License, Version 2.0'

Parameters:
  CcApiKey:
    NoEcho: true
    Description: Cloud Connector API Key
    Type: String
  CcUser:
    NoEcho: true
    Description: Cloud Connector Provisioning Username
    Type: String
  CcPass:
    NoEcho: true
    Description: Cloud Connector Provisioning Password
    Type: String
  SecretManagerSecretName:
    Type: String
    Description: >-
      Secret Manager Secret Name, defaults to ZS/CC/credentials
    
# Create AWS Secrets for Cloud Connector API Key and Provisioning Credentials
Resources:
  ZSCCSecrets:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Zscaler Cloud Connector Secrets
      SecretString: !Join
        - ''
        - - '{"api_key": "'
          - !Ref CcApiKey
          - '","username":"'
          - !Ref CcUser
          - '","password":"'
          - !Ref CcPass
          - '"}'
      Name: !Ref SecretManagerSecretName
